#!/usr/bin/python3
import os
import sys
from colorama import Fore, Back
RED, YELLOW, GREEN, CYAN, WHITE, RESET =\
  Fore.RED, Fore.YELLOW, Fore.GREEN, Fore.CYAN, Fore.WHITE, Fore.RESET+Back.RESET
BYELLOW = Back.YELLOW

def getCharRepr(c: str, pos: bool):
  COLOR = BYELLOW if (pos) else ""
  if (ord(c) == 0):
    return f"{COLOR}{RED}~{RESET}"
  elif (ord(c) == 4):
    return f"{COLOR}{RED}E{RESET}"
  elif (ord(c) == 5):
    return f"{COLOR}{RED}Q{RESET}"
  elif (ord(c) == 8):
    return f"{COLOR}{RED}B{RESET}"
  elif (ord(c) == 9):
    return f"{COLOR}{RED}T{RESET}"
  elif (ord(c) == 10):
    return f"{COLOR}{RED}↓{RESET}"
  elif ((ord(c) >= 32) and (ord(c) < 127)):
    return f"{COLOR}{WHITE}{c}{RESET}"
  elif (ord(c) == 127):
    return f"{COLOR}{RED}D{RESET}"
  else:
    return f"{COLOR}{RED}.{RESET}"

def printBuf(buf: list, sep: int, cpos: int):
  if (not buf):
    print(f"{RED}No data.{RESET}")
  else:
    print(f"\n{' '*12} {GREEN}0123456789ABCDEF{RESET}", end="")
    for pos, c in enumerate(buf):
      if ((pos % sep == 0)):
        print(f"\n{CYAN}[0x{hex(pos)[2:].upper():0>8}]{RESET} ", end="")
      print(getCharRepr(c, (cpos == pos)), end="")
    print("\n")

def main(argc: int, argv: list):
  if (not argv[1:]):
    argv.append("unnamed.out")
  if (not os.path.exists(argv[1])):
    with open(argv[1], "w"):
      pass
  with open(argv[1], "rb") as fl:
    buf: str = [chr(i) for i in fl.read()]
  pos: int = 0
  sep: int = 16

  while (True):
    com = input(f"{YELLOW}[0x{hex(pos)[2:].upper():0>8}]{RESET} -> ")
    if (com == ""):
      pass
    elif (com == "q"):
      break
    elif (com == "s"):
      with open(argv[1], "w") as fl:
        fl.write("".join(buf))
      print(f"File saved into {argv[1]}")
    elif (com[0] == "w"):
      for i in com[1:].split():
        buf[pos] = chr(int(i, base=16))
        pos += 1
    elif (com[0] == "W"):
      for i in com[1:].split():
        buf.insert(pos, chr(int(i, base=16)))
        pos += 1
    elif (com[:2] == "S "):
      val = int(com[2:])
      if (len(buf) < val):
        while (len(buf) < val):
          buf += "\0"
      elif (len(buf) > val):
        while (len(buf) > val):
          buf = buf[:-1]
    elif (com[:2] == "S+"):
      buf += "\0"*int(com[2:])
    elif (com[:2] == "S-"):
      buf = buf[:-int(com[2:])]
    elif (com[:2] == "E "):
      sep = int(com[2:])
    elif (com[:3] == "Hc "):
      for i in com[3:]:
        print(f"{GREEN}{hex(ord(i))[2:].upper():0<2}{RESET}", end=" ")
      print("\b")
    elif (com[:2] == "B "):
      for i in range(int(com[2:])):
        pos -= 1
        buf[pos] = "\0"
    elif (com[:2] == "r "):
      val = com[2:].split()
      if (len(val) != 2):
        print(f"`r` expected 2 arguments")
        continue
      for i in range(int(val[0])):
        buf[pos] = chr(int(val[1], base=16))
        pos += 1
    elif (com[:2] == "P "):
      pos = int(com[2:])
    elif (com[:2] == "PF"):
      pos += int(com[2:])
    elif (com[:2] == "PB"):
      pos -= int(com[2:])
    elif (com == "p"):
      printBuf(buf, sep, pos)
    else:
      print(f"Unknown command `{com}`")
  return 0;

if (__name__ == "__main__"):
  exit(main(len(sys.argv), sys.argv))

